### ISSUE TITLE
UnicodeDecodeError While generating yolov5s.wts

### ISSUE THREAD

**Issue by imSrbh** [marcoslucianops/DeepStream-Yolo#111]
@marcoslucianops I'm facing this issue while generating wts

 `wget https://github.com/ultralytics/yolov5/releases/download/v6.0/yolov5s.pt`
`python3 gen_wts_yoloV5.py -w yolov5s.pt`

```
(env) root@c9ff04c856cb:/opt/nvidia/deepstream/deepstream-6.0/DeepStream-Yolo/yolov5# python3 gen_wts_yoloV5.py -w yolov5s.pt
YOLOv5 \U0001f680 v6.0-148-gc1249a4 torch 1.10.1+cu102 CPU

Traceback (most recent call last):
  File "gen_wts_yoloV5.py", line 117, in <module>
    f = yaml.load(f,Loader=yaml.FullLoader)
  File "/opt/nvidia/deepstream/deepstream-6.0/DeepStream-Yolo/yolov5/env/lib/python3.6/site-packages/yaml/__init__.py", line 79, in load
    loader = Loader(stream)
  File "/opt/nvidia/deepstream/deepstream-6.0/DeepStream-Yolo/yolov5/env/lib/python3.6/site-packages/yaml/loader.py", line 24, in __init__
    Reader.__init__(self, stream)
  File "/opt/nvidia/deepstream/deepstream-6.0/DeepStream-Yolo/yolov5/env/lib/python3.6/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/opt/nvidia/deepstream/deepstream-6.0/DeepStream-Yolo/yolov5/env/lib/python3.6/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/opt/nvidia/deepstream/deepstream-6.0/DeepStream-Yolo/yolov5/env/lib/python3.6/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 9: ordinal not in range(128)
```

**Comment by BTVinh0409** [comment]
Hi @imSrbh, you should pass encoding='utf-8' at line 108 of gen_wts_yoloV5.py. It worked for me
```
with open(yaml_file, "r", encoding="utf-8") as f
```

**Comment by imSrbh** [comment]
@BTVinh0409 Yeah
