### ISSUE TITLE
.engine generated successfully but not works

### ISSUE THREAD

**Issue by javiercalle97** [marcoslucianops/DeepStream-Yolo#141]
After generate the .engine successfully I have tried to infer some images with yolov5 (loading that .engine model), but doesn't work. 
`python3 detect.py --weights model_b1_gpu0_fp32.engine --source datasets/prueba --device 0`
The error showed is: 

``` python3

detect: weights=['model_b1_gpu0_fp32.engine'], source=datasets/prueba, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=0, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False
YOLOv5 🚀 c659ed0 torch 1.9.0 CUDA:0 (Xavier, 31921MiB)

Loading model_b1_gpu0_fp32.engine for TensorRT inference...
[TensorRT] INFO: [MemUsageChange] Init CUDA: CPU +353, GPU +0, now: CPU 441, GPU 23420 (MiB)
[TensorRT] INFO: Loaded engine size: 46 MB
[TensorRT] INFO: [MemUsageSnapshot] deserializeCudaEngine begin: CPU 488 MiB, GPU 23467 MiB
[TensorRT] ERROR: 3: getPluginCreator could not find plugin: YoloLayer_TRT version: 1
[TensorRT] ERROR: 1: [pluginV2Runner.cpp::load::292] Error Code 1: Serialization (Serialization assertion creator failed.Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
[TensorRT] ERROR: 4: [runtime.cpp::deserializeCudaEngine::76] Error Code 4: Internal Error (Engine deserialization failed.)
Traceback (most recent call last):
  File "detect.py", line 259, in <module>
    main(opt)
  File "detect.py", line 254, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 92, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data)
  File "/opt/app/yolo5/models/common.py", line 346, in __init__
    for index in range(model.num_bindings):
AttributeError: 'NoneType' object has no attribute 'num_bindings'
``` 

But if I run the .engine generated with the yolov5 export works perfect. 

How can I fixed this?

**Comment by marcoslucianops** [comment]
The engine generated from this repo works only in DeepStream-Yolo files. You can't use it in PyTorch YOLOv5.

**Comment by javiercalle97** [comment]
Okay perfect, I have tried it in the Jetson board and works perfect, thanks for answer that quick!
