### ISSUE TITLE
gen_wts_yoloV5.py - UnicodeDecodeError

### ISSUE THREAD

**Issue by JWLee89** [marcoslucianops/DeepStream-Yolo#149]
Hello, 

I tried following the steps described using the steps provided under YOLOv5 usage. 
The error occurs in step 4 

4. Generate cfg and wts files (example for YOLOv5n)
```shell
python3 gen_wts_yoloV5.py -w yolov5n.pt
```

I get the following error: 

```
/root/yolov5# python3 gen_wts_yoloV5.py -w yolov5n.pt
YOLOv5 \U0001f680 v6.1-21-ge6e36aa torch 1.10.1+cu113 CPU

Traceback (most recent call last):
  File "gen_wts_yoloV5.py", line 133, in <module>
    f = yaml.load(f,Loader=yaml.FullLoader)
  File "/usr/local/lib/python3.6/dist-packages/yaml/__init__.py", line 79, in load
    loader = Loader(stream)
  File "/usr/local/lib/python3.6/dist-packages/yaml/loader.py", line 24, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/lib/python3.6/dist-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/usr/local/lib/python3.6/dist-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/usr/local/lib/python3.6/dist-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 9: ordinal not in range(128)
```
I was wondering if anybody else is getting this error. I am using cuda 11.4 and running this script under the DeepStream Devel container provided by Nvidia.

**Comment by JWLee89** [comment]
Update: I fixed this error. Will make a PR right away.

**Comment by marcoslucianops** [comment]
Thank you.
