### ISSUE TITLE
May I ask what? My onnx always fails to install

### ISSUE THREAD

**Issue by ghty11468** [marcoslucianops/DeepStream-Yolo#429]
Building wheels for collected packages: onnx
  Building wheel for onnx (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpdoctmk8g
       cwd: /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924
  Complete output (188 lines):
  fatal: not a git repository (or any of the parent directories): .git
  running bdist_wheel
  running build
  running build_py
  running create_version
  running cmake_build
  Using cmake args: ['/usr/bin/cmake', '-DPYTHON_INCLUDE_DIR=/usr/include/python3.6m', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-36m-aarch64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924']
  -- The C compiler identification is GNU 7.5.0
  -- The CXX compiler identification is GNU 7.5.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found PythonInterp: /usr/bin/python3 (found version "3.6.9")
  -- Found PythonLibs: /usr/lib/aarch64-linux-gnu/libpython3.6m.so (found version "3.6.9")
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Looking for pthread_create
  -- Looking for pthread_create - not found
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - found
  -- Found Threads: TRUE
  -- Found Protobuf: /usr/lib/aarch64-linux-gnu/libprotobuf.a;-lpthread (found version "3.0.0")
  Generated: /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/.setuptools-cmake-build/onnx/onnx-ml.proto
  Generated: /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
  Generated: /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/.setuptools-cmake-build/onnx/onnx-data.proto
  -- Could NOT find pybind11 (missing: pybind11_DIR)
  -- pybind11 v2.10.3
  -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3.6")
  -- Found PythonLibs: /usr/lib/aarch64-linux-gnu/libpython3.6m.so
  -- Performing Test HAS_FLTO
  -- Performing Test HAS_FLTO - Success
  --
  -- ******** Summary ********
  --   CMake version             : 3.10.2
  --   CMake command             : /usr/bin/cmake
  --   System                    : Linux
  --   C++ compiler              : /usr/bin/c++
  --   C++ compiler version      : 7.5.0
  --   CXX flags                 :  -Wnon-virtual-dtor
  --   Build type                : Release
  --   Compile definitions       : __STDC_FORMAT_MACROS
  --   CMAKE_PREFIX_PATH         :
  --   CMAKE_INSTALL_PREFIX      : /usr/local
  --   CMAKE_MODULE_PATH         :
  --
  --   ONNX version              : 1.14.0
  --   ONNX NAMESPACE            : onnx
  --   ONNX_USE_LITE_PROTO       : OFF
  --   USE_PROTOBUF_SHARED_LIBS  : OFF
  --   Protobuf_USE_STATIC_LIBS  : ON
  --   ONNX_DISABLE_EXCEPTIONS   : OFF
  --   ONNX_WERROR               : OFF
  --   ONNX_BUILD_TESTS          : OFF
  --   ONNX_BUILD_BENCHMARKS     : OFF
  --
  --   Protobuf compiler         : /usr/bin/protoc
  --   Protobuf includes         : /usr/include
  --   Protobuf libraries        : /usr/lib/aarch64-linux-gnu/libprotobuf.a;-lpthread
  --   BUILD_ONNX_PYTHON         : ON
  --     Python version        :
  --     Python executable     : /usr/bin/python3
  --     Python includes       : /usr/include/python3.6m
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/.setuptools-cmake-build
  Scanning dependencies of target gen_onnx_proto
  [  1%] Running gen_proto.py on onnx/onnx.in.proto
  Processing /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/onnx/onnx.in.proto
  Writing /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/.setuptools-cmake-build/onnx/onnx-ml.proto
  Writing /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/.setuptools-cmake-build/onnx/onnx-ml.proto3
  generating /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/.setuptools-cmake-build/onnx/onnx_pb.py
  [  2%] Running C++ protocol buffer compiler on /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/.setuptools-cmake-build/onnx/onnx-ml.proto
  Failed to generate mypy stubs: No module named 'google'
  [  2%] Built target gen_onnx_proto
  Scanning dependencies of target gen_onnx_operators_proto
  Scanning dependencies of target gen_onnx_data_proto
  [  5%] Running gen_proto.py on onnx/onnx-operators.in.proto
  [  5%] Running gen_proto.py on onnx/onnx-data.in.proto
  Processing /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/onnx/onnx-operators.in.proto
  Writing /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
  Writing /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/.setuptools-cmake-build/onnx/onnx-operators-ml.proto3
  generating /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/.setuptools-cmake-build/onnx/onnx_operators_pb.py
  Processing /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/onnx/onnx-data.in.proto
  Writing /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/.setuptools-cmake-build/onnx/onnx-data.proto
  Writing /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/.setuptools-cmake-build/onnx/onnx-data.proto3
  generating /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/.setuptools-cmake-build/onnx/onnx_data_pb.py
  [  8%] Running C++ protocol buffer compiler on /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
  [  8%] Running C++ protocol buffer compiler on /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/.setuptools-cmake-build/onnx/onnx-data.proto
  Failed to generate mypy stubs: No module named 'google'
  Failed to generate mypy stubs: No module named 'google'
  [  8%] Built target gen_onnx_operators_proto
  [  8%] Built target gen_onnx_data_proto
  Scanning dependencies of target onnx_proto
  [ 13%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-ml.pb.cc.o
  [ 13%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-data.pb.cc.o
  [ 13%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-operators-ml.pb.cc.o
  [ 14%] Linking CXX static library libonnx_proto.a
  [ 23%] Built target onnx_proto
  Scanning dependencies of target onnx
  [ 29%] Building CXX object CMakeFiles/onnx.dir/onnx/common/assertions.cc.o
  [ 29%] Building CXX object CMakeFiles/onnx.dir/onnx/common/interned_strings.cc.o
  [ 29%] Building CXX object CMakeFiles/onnx.dir/onnx/checker.cc.o
  [ 29%] Building CXX object CMakeFiles/onnx.dir/onnx/common/ir_pb_converter.cc.o
  [ 30%] Building CXX object CMakeFiles/onnx.dir/onnx/common/model_helpers.cc.o
  In file included from /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/onnx/defs/schema.h:25:0,
                   from /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/onnx/defs/function.h:16,
                   from /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/onnx/checker.h:10,
                   from /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/onnx/checker.cc:5:
  /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/onnx/defs/shape_inference.h: In function ‘void onnx::adjustNegativeAxes(Axes&, int)’:
  /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/onnx/defs/shape_inference.h:828:8: error: ‘transform’ is not a member of ‘std’
     std::transform(
          ^~~~~~~~~
  In file included from /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/onnx/defs/schema.h:25:0,
                   from /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/onnx/defs/function.h:16,
                   from /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/onnx/checker.h:10,
                   from /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/onnx/common/model_helpers.cc:6:
  /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/onnx/defs/shape_inference.h: In function ‘void onnx::adjustNegativeAxes(Axes&, int)’:
  /tmp/pip-install-e_sc_uyi/onnx_76dbac978a414bae942721475d81a924/onnx/defs/shape_inference.h:828:8: error: ‘transform’ is not a member of ‘std’
     std::transform(
          ^~~~~~~~~
  CMakeFiles/onnx.dir/build.make:158: recipe for target 'CMakeFiles/onnx.dir/onnx/common/model_helpers.cc.o' failed
  make[2]: *** [CMakeFiles/onnx.dir/onnx/common/model_helpers.cc.o] Error 1
  make[2]: *** Waiting for unfinished jobs....
  CMakeFiles/onnx.dir/build.make:62: recipe for target 'CMakeFiles/onnx.dir/onnx/checker.cc.o' failed
  make[2]: *** [CMakeFiles/onnx.dir/onnx/checker.cc.o] Error 1
  CMakeFiles/Makefile2:202: recipe for target 'CMakeFiles/onnx.dir/all' failed
  make[1]: *** [CMakeFiles/onnx.dir/all] Error 2
  Makefile:129: recipe for target 'all' failed
  make: *** [all] Error 2
  Traceback (most recent call last):
    File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 262, in build_wheel
      metadata_directory)
    File "/usr/local/lib/python3.6/dist-packages/setuptools/build_meta.py", line 231, in build_wheel
      wheel_directory, config_settings)
    File "/usr/local/lib/python3.6/dist-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "/usr/local/lib/python3.6/dist-packages/setuptools/build_meta.py", line 268, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/usr/local/lib/python3.6/dist-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 365, in <module>
      "backend-test-tools = onnx.backend.test.cmd_tools:main",
    File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-xpz8q24z/overlay/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "setup.py", line 236, in run
      self.run_command("cmake_build")
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "setup.py", line 230, in run
      subprocess.check_call(build_args)
    File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '.', '--', '-j', '4']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for onnx
Failed to build onnx
ERROR: Could not build wheels for onnx, which is required to install pyproject.toml-based projects

**Comment by ghty11468** [comment]
This problem has been solved. The method is to reduce the version of onnx
